### ISSUE TITLE
Issues validating a user-created organization

### ISSUE THREAD

**Issue by kerriedochen** [phetsims/website-meteor#28] opened 2017-11-29 22:40 UTC
Under https://ox-dev.colorado.edu/admin/organizations when you try to validate or invalidate an organization by clicking the check/x button and then click through the pop-ups, it does not actually update the validation. Then, if you click one of the other buttons (edit, link, or delete), the validation will update suddenly. 

This bug does not appear to be present for https://ox-dev.colorado.edu/admin/schools

Using Mac 10.13.1 Firefox 56.0.2
For https://github.com/phetsims/QA/issues/70

**Comment by mattpen** [comment] 2017-12-04 23:22
This should be fixed, although the behavior is a little curious.  The handling of (in)validation for organizations and schools is exactly identical.  I only observed this behavior if there were multiple pages of data and you change something after the first page.  I added a call to refresh the UI a half second after changes take place (in addition to when they take place). This does not solve the root cause but hopefully it solves the problem well enough.

@kerriedochen @phet-steele - Can you please confirm that the behavior is now as expected?

**Comment by phet-steele** [comment] 2017-12-07 18:31
I've seen no issues with the force update yet, but will let @kerriedochen verify as well.

**Closed** 2017-12-13 23:23 UTC
Labels: status:fixed-pending-testing, type:bug
